# Generated by Django 4.1.3 on 2024-07-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0002_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
