# Generated by Django 4.1.3 on 2024-07-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0005_course_category_alter_course_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
