# Generated by Django 4.1.3 on 2024-07-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0007_alter_category_slug_alter_course_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(to="Courses.category"),
        ),
    ]
