# Generated by Django 4.1.3 on 2024-07-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0010_upload_alter_course_imageurl_alter_course_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="imageUrl",
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(default="", upload_to="images"),
        ),
    ]
