# Generated by Django 4.1.3 on 2024-07-30 09:11

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0011_remove_course_imageurl_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="subtitle",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
